# Generated by Django 2.0.2 on 2018-03-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180306_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
    ]
