# Generated by Django 2.0.2 on 2018-03-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180317_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='page_status',
            field=models.CharField(choices=[('success', '成功'), ('cancel', '取消'), ('cancel', '待支付')], default='success', max_length=10, verbose_name='订单状态'),
        ),
    ]
