# Generated by Django 2.0.2 on 2018-03-18 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180318_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordergoods', to='trade.OrderInfo', verbose_name='订单信息'),
        ),
    ]
