# Generated by Django 2.0.2 on 2018-04-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20180318_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='page_status',
            new_name='pay_status',
        ),
    ]
