# Generated by Django 2.0.2 on 2018-03-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20180313_2019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set(),
        ),
    ]
