# Generated by Django 2.0.2 on 2018-03-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0007_auto_20180314_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userleavingmessage',
            name='msg_type',
        ),
        migrations.RemoveField(
            model_name='userleavingmessage',
            name='update_time',
        ),
        migrations.AddField(
            model_name='userleavingmessage',
            name='message',
            field=models.TextField(default='', help_text='留言内容', verbose_name='留言内容'),
        ),
        migrations.AddField(
            model_name='userleavingmessage',
            name='message_type',
            field=models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')], default=1, help_text='留言类型: 1(留言),2(投诉),3(询问),4(售后),5(求购)', verbose_name='留言类型'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='商品id', on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='subject',
            field=models.CharField(default='', max_length=100, verbose_name='主题'),
        ),
    ]
