# Generated by Django 2.0.2 on 2018-03-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0009_auto_20180315_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='update_time',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='省份'),
        ),
    ]
